version: "3"

services:
  app:
    build: .
    container_name: simulator
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:192.168.0.14"